version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: lot_fast_test
    restart: always
    ports:
      - 7000:7000
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64